server:
  port: 8080
spring:
  application:
    name: base-project
  datasource:
    username: root
    password: DES@2120FA78BC6EB99B019C119BD8067DB0
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# redis 配置
#  redis:
#    host: 116.205.181.9
#    port: 6379
#    password: DES@2120FA78BC6EB99B019C119BD8067DB0


# xxl job 配置
#job:
#  adminAddresses: http://127.0.0.1:6850/xxl-job-admin
#  appName: auth-executor
#  logPath: /data/jobhandler
#  logRetentionDays: 4
#  enable: false

# rocketmq 配置
#rocketmq:
#  nameServer: 127.0.0.1:9876
#  producer:
#    group: boot-demo