spring:
  datasource:
    username: root
    password: DES@2120FA78BC6EB99B019C119BD8067DB0
    url: jdbc:mysql://localhost:3306/base_sync?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 119.91.30.131
    port: 6379
    password: DES@2120FA78BC6EB99B019C119BD8067DB0

jdbc:
  common$maxIdle: 20
  common$maxWait: 1000
  common$minIdle: 10
  common$maxActive: 800
  common$timeout: 20
  mysql$username: root
  mysql$password: 123456
  mysql$initialSize: 10
  mysql$minEvictableIdleTimeMillis: 10000
  mysql$timeBetweenEvicationRunsMills: 10000
  mysql$testOnBorrow: false
  mysql$testOnReturn: false
  mysql$testWhileIdle: true
  # 业务系统1
  demo$url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  demo$username: root
  demo$password: 2120FA78BC6EB99B019C119BD8067DB0
  # 业务系统2
  demo2$url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  demo2$username: root
  demo2$password: 2120FA78BC6EB99B019C119BD8067DB0

