spring:
  datasource:
    druid:
      username: root
      password: DES@2120FA78BC6EB99B019C119BD8067DB0
      url: jdbc:mysql://localhost:3306/base_sync?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 116.205.181.9
    port: 6379
    password: DES@2120FA78BC6EB99B019C119BD8067DB0

job:
  adminAddresses: http://127.0.0.1:6850/xxl-job-admin
  appName: sync-executor
  logPath: /data/jobhandler
  logRetentionDays: 4
  enable: true

sync:
  # es 配置
  elasticsearch:
    cluster-name: sync_es_cluster
    hosts: 116.205.181.9:9200
    scheme: http
    connect-time-out: 2000
    socket-time-out: 30000
    connection-request-time-out: 500
    max-connect-num: 100
    max-connect-num-per-route: 100
  # rocketmq配置
  rocketmq:
    namesrv-addr: 116.205.181.9:9876
    instance-name: SyncServer
    consumer-group: SyncConsumer
    topic: SyncTopic
    consume-thread-min: 20
    consume-thread-max: 40
  # 同步回调配置
  callback:
    dest-list:
      - project: demo
        url: http://127.0.0.1:8084



jdbc:
  common$maxIdle: 20
  common$maxWait: 1000
  common$minIdle: 10
  common$maxActive: 800
  common$timeout: 20
  mysql$username: root
  mysql$password: 123456
  mysql$initialSize: 10
  mysql$minEvictableIdleTimeMillis: 40000
  mysql$timeBetweenEvictionRunsMillis: 10000
  mysql$testOnBorrow: false
  mysql$testOnReturn: false
  mysql$testWhileIdle: true
  # 业务系统1
  datasource1$url: jdbc:mysql://localhost:3306/datasource1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  datasource1$username: root
  datasource1$password: 2120FA78BC6EB99B019C119BD8067DB0
  # 业务系统2
  datasource2$url: jdbc:mysql://localhost:3306/datasource2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  datasource2$username: root
  datasource2$password: 2120FA78BC6EB99B019C119BD8067DB0