spring:
  datasource:
    druid:
      username: root
      password: DES@2120FA78BC6EB99B019C119BD8067DB0
      url: jdbc:mysql://localhost:3306/datasource1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 119.91.30.131
    port: 6379
    password: DES@2120FA78BC6EB99B019C119BD8067DB0

rocketmq:
  nameServer: 119.91.30.131:9876
  producer:
    group: boot-demo

jdbc:
  common$maxIdle: 20
  common$maxWait: 1000
  common$minIdle: 10
  common$maxActive: 800
  common$timeout: 20
  mysql$username: root
  mysql$password: 123456
  mysql$initialSize: 10
  mysql$minEvictableIdleTimeMillis: 40000
  mysql$timeBetweenEvictionRunsMillis: 10000
  mysql$testOnBorrow: false
  mysql$testOnReturn: false
  mysql$testWhileIdle: true
  # 业务系统1
  datasource1$url: jdbc:mysql://localhost:3306/datasource1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  datasource1$username: root
  datasource1$password: 2120FA78BC6EB99B019C119BD8067DB0
  # 业务系统2
  datasource2$url: jdbc:mysql://localhost:3306/datasource2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  datasource2$username: root
  datasource2$password: 2120FA78BC6EB99B019C119BD8067DB0

