spring:
  datasource:
    druid:
      username: root
      password: DES@2120FA78BC6EB99B019C119BD8067DB0
      url: jdbc:mysql://localhost:3306/base_sync?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

job:
  adminAddresses: http://127.0.0.1:6850/xxl-job-admin
  appName: sync-executor
  logPath: /data/jobhandler
  logRetentionDays: 4
  enable: true

sync:
  # es 配置
  elasticsearch:
    cluster-name: sync_es_cluster
    hosts: 127.0.0.1:9200
    scheme: http
    connect-time-out: 5000
    socket-time-out: 60000
    connection-request-time-out: 500
    max-connect-num: 100
    max-connect-num-per-route: 100
  # rocketmq配置
  rocketmq:
    namesrv-addr: 103.133.179.32:9876
    instance-name: SyncServer
    consumer-group: SyncConsumer
    consumer-order-group: SyncOrderConsumer
    topic: SyncTopic
    order-topic: SyncOrderTopic
    consume-thread-min: 20
    consume-thread-max: 40
  # 同步回调配置
  callback:
    dest-list:
      - project: demo
        url: http://127.0.0.1:8084
  # 同步系统jdbc配置
  jdbc:
    commonMaxIdle: 20
    commonMaxWait: 1000
    commonMinIdle: 10
    commonMaxActive: 800
    commonTimeout: 20
    mysqlUsername: root
    mysqlPassword: 123456
    mysqlInitialSize: 10
    mysqlMinEvictableIdleTimeMillis: 40000
    mysqlTimeBetweenEvictionRunsMillis: 10000
    mysqlTestOnBorrow: false
    mysqlTestOnReturn: false
    mysqlTestWhileIdle: true
    dbList:
      - dbname: datasource1
        url: jdbc:mysql://localhost:3306/datasource1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: DES@2120FA78BC6EB99B019C119BD8067DB0
        callback: true
        message: true

      - dbname: datasource2
        url: jdbc:mysql://localhost:3306/datasource2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: DES@2120FA78BC6EB99B019C119BD8067DB0
        callback: true
        message: true

      - dbname:  ecp_cart_dev
        url: 127.0.0.1:27017
        connectionsPerHost: 50
        connectTimeout: 1000
        type: mongo
        maxWaitTime: 1500
        serverSelectionTimeout: 10000
        socketKeepAlive: true
        socketTimeout: 600000
        threadsAllowedToBlockForConnectionMultiplier: 20
        username: root
        password:  DES@2120FA78BC6EB99B019C119BD8067DB0



logging:
  level:
    root: info
    com.coderman.sync: info
