server:
  port: 8081
spring:
  application:
    name: base-auth
  datasource:
    username: root
    password: zhangyukang
    url: jdbc:mysql://localhost:3306/base_auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    auth:
      host: 119.91.30.131
      port: 6379
      password: zhangyukang

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#rocketmq:
#  nameServer: 127.0.0.1:9876
#  producer:
#    group: boot-demo