server:
  port: 8082
spring:
  application:
    name: base-auth
  datasource:
    username: root
    password: DES@2120FA78BC6EB99B019C119BD8067DB0
    url: jdbc:mysql://localhost:3306/base_auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    auth:
      host: 119.91.30.131
      port: 6379
      password: DES@2120FA78BC6EB99B019C119BD8067DB0

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# xxl job 配置
job:
  adminAddresses: http://119.91.30.131:6850/xxl-job-admin
  appName: auth-executor
  logPath: /data/jobhandler
  logRetentionDays: 4
  enable: false

# 权限服务安全码
auth:
  erp:
    auth-security-code: coderman



#rocketmq:
#  nameServer: 127.0.0.1:9876
#  producer:
#    group: boot-demo